Repository crowbartools/Firebot, pull requests merged in 2020-02, with the labels that each got.

#663 Allow reading and deleting specific lines in files.
  backend/common/handlers/fileWriterProcessor.js
  backend/effects/builtin/fileWriter.js
  backend/variables/builtin-variable-loader.js
  backend/variables/builtin/fileLineCount.js
  backend/variables/builtin/readFile.js
Labels: In Development

#666 Add ability to get a random image from a folder.
  backend/effects/builtin/showImage.js
Labels: Improvement

#678 v5.6.2 Release
  .github/workflows/build-draft-release.yml
  backend/common/handlers/chatProcessor.js
  backend/common/mixer-chat.js
  backend/database/userDatabase.js
  backend/live-events/filters/builtin-filter-loader.js
  backend/live-events/filters/builtin/message-type.js
  backend/live-events/filters/builtin/message.js
  backend/variables/builtin-variable-loader.js
  backend/variables/builtin/top-currency.js
  backend/variables/builtin/top-view-time.js
  package.json
Labels: New Release
